service: serverlessdemo1
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  imageResize:
    handler: handler.imageResize
    events:
      - http:
          path: /imageResize
          method: get
